theme = "custom"

[editor]
color-modes = true
popup-border = "all"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[keys.normal]
C-q = ":quit-all"
C-s = ":write"
C-w = ":buffer-close"
