[[language]]
name = "rust"
[language.indent]
unit = "\t"
tab-width = 4
[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "python"
language-servers = ["pyright", "ruff"]
auto-format = true
[language.indent]
unit = "\t"
tab-width = 4
[language.formatter]
command = "black"
args = ["--line-length=88", "--quiet", "-"]
[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"
[language-server.ruff]
command = "ruff-lsp"
[language-server.ruff.config.settings]
args = ["--ignore=E501"]
