[[language]]
name = "rust"
[language.indent]
unit = "\t"
tab-width = 4
[language-server.rust-analyzer.config.cargo]
features = "all"
[language-server.rust-analyzer.config.check]
command = "clippy"
[language-server.rust-analyzer.config.imports]
prefix = "self"

[language-server.zls.config]
enable_build_on_save = true

[[language]]
name = "python"
language-servers = ["pylyzer", "ruff"]
auto-format = true
[language.indent]
unit = "\t"
tab-width = 4
[language.formatter]
command = "ruff"
args = ["format", "--quiet", "-"]
# [language-server.pyright.config.python.analysis]
# typeCheckingMode = "basic"
[language-server.ruff]
command = "ruff"
args = ["server"]

[[language]]
name = "brioche"
language-id = "typescript"
scope = "source.brioche"
injection-regex = "bri(oche)?"
file-types = ["bri"]
grammar = "typescript"
comment-token = "//"
block-comment-tokens = { start = "/*", end = "*/" }
language-servers = ["brioche"]
[language.indent]
unit = "\t"
tab-width = 4
[language-server.brioche]
command = "brioche"
args = ["lsp", "--stdio"]
