[[language]]
name = "rust"
[language.indent]
unit = "\t"
tab-width = 4
[language-server.rust-analyzer.config.cargo]
features = "all"
[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "python"
language-servers = ["pyright", "ruff"]
auto-format = true
[language.indent]
unit = "\t"
tab-width = 4
[language.formatter]
command = "black"
args = ["--line-length=88", "--quiet", "-"]
[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"
[language-server.ruff]
command = "ruff-lsp"
[language-server.ruff.config.settings]
args = ["--ignore=E501"]

[[language]]
name = "brioche"
language-id = "typescript"
scope = "source.brioche"
injection-regex = "bri(oche)?"
file-types = ["bri"]
grammar = "typescript"
comment-token = "//"
block-comment-tokens = { start = "/*", end = "*/" }
language-servers = ["brioche"]
[language.indent]
unit = "\t"
tab-width = 4
[language-server.brioche]
command = "brioche"
args = ["lsp", "--stdio"]
