windowrule {
	name = firefox-pip
	match:initial_class = ^firefox$
	match:initial_title = ^Picture-in-Picture$

	content = video
}

# Games
windowrule {
	name = steam
	match:initial_class = ^steam_app_\d+$

	content = game
}
windowrule {
	name = minecraft
	match:initial_title = ^Minecraft.*

	content = game
}
windowrule {
	name = scrcpy
	match:initial_class = ^scrcpy$

	content = game
}
