import:
  timid: true
  reflink: auto

musicbrainz:
  genres: true

paths:
  default: "$album%aunique{}/$disc_and_track $title"
  comp: "$album%aunique{}/$disc_and_track $title"
  singleton: "[Singles]/$title%sunique{}"


plugins:
  - autobpm
  - chroma
  - edit
  - embedart
  - fetchart
  - fromfilename
  - info
  - inline
  - lyrics
  - mbsync
  - missing
  - mpdupdate
  - replaygain
  - thumbnails
  - zero

fetchart:
  enforce_ratio: true

item_fields: # Inline Plugin
  disc_and_track: u'%01i-%02i' % (disc, track) if disctotal > 1 else u'%02i' % (track)

missing:
  count: true
  total: true

replaygain:
  backend: gstreamer

zero:
  fields: comments
  update_database: true
  comments:
    - '^(https?://)?www\.'
