#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[ui]
default-command = "status"

[git]
sign-on-push = true

[signing]
behavior = "drop"

[revset-aliases.HEAD]
doc = "The parent of the working-copy commit"
definition = '@-'
[revset-aliases.'grep:re']
doc = "Matches commit descriptions with the regex"
definition = 'description(regex-i:re)'

[template-aliases]
'format_timestamp(timestamp)' = 'timestamp.format("%a %d %b %Y %T %Z")'
'format_short_signature(signature)' = 'signature.name()'
'commit_timestamp(commit)' = 'commit.author().timestamp()'
