#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[ui]
default-command = "status"

[git]
sign-on-push = true

[template-aliases]
'format_timestamp(timestamp)' = 'timestamp.local().format("%c")'
'format_short_signature(signature)' = 'signature.name()'
'commit_timestamp(commit)' = 'commit.author().timestamp()'

[revset-aliases.HEAD]
definition = '@-'
doc = "The parent of the working-copy commit"
