[tools]
bat = "latest"
delta = "latest"
eza = "latest"
git = "latest"
"cargo:git-interactive-rebase-tool" = "latest"
"ubi:charmbracelet/glow" = "latest"
"ubi:doronbehar/pistol" = "latest"
starship = "latest"
usage = "latest"

# Shell
gum = "latest"
shellcheck = "latest"
# Rust
#rust = ["stable", "nightly"]
rust-analyzer = "latest"
"cargo:cargo-outdated" = "latest"
"cargo:cargo-expand" = "latest"
"cargo:cargo-modules" = "latest"
# Zig
zig = "latest"
"ubi:zigtools/zls" = "latest"
"pipx:zigcc" = "latest"
# Python
python = "latest"
"cargo:pylyzer" = "latest"
"pipx:ruff" = "latest"
# Node.js
node = "latest"
# Typst
typst = "latest"
"ubi:Myriad-Dreamin/tinymist" = "latest"

# Backends
pipx = "latest"
ubi = "latest"
"cargo:typstyle" = "latest"

[env]
AR = "zig ar"
CC = "zigcc"
CXX = "zigcxx"


[settings]
experimental = true

not_found_auto_install = false
