[settings]
experimental = true

not_found_auto_install = false


[tools]
usage = "latest"
starship = "latest"

# Shell
shellcheck = "latest"
# Rust
# rust = ["stable", "nightly"]
rust-analyzer = "latest"
"cargo:cargo-expand" = "latest"
"cargo:cargo-modules" = "latest"
# Python
python = "latest"
"cargo:pylyzer" = "latest"
"pipx:ruff" = "latest"
# Node.js
node = "latest"

# Backends
pipx = "latest"
ubi = "latest"
