[settings]
experimental = true

not_found_auto_install = false


[tools]
usage = "latest"

# Shell
shellcheck = "latest"
# Rust
# rust = ["stable", "nightly"]
rust-analyzer = "latest"
"cargo:cargo-expand" = "latest"
# Python
python = "latest"
"pipx:ruff" = "latest"
"npm:pyright" = "latest"
"pipx:black" = "latest"
# Node.js
node = "latest"
