[tools]
# Backends
pipx = "latest"
ubi = "latest"

# Tools
bat = "latest"
"cargo:cargo-binstall" = "latest"
delta = "latest"
eza = "latest"
git = "latest"
"cargo:git-interactive-rebase-tool" = "latest"
"ubi:charmbracelet/glow" = "latest"
"ubi:noborus/ov" = "latest"
"ubi:doronbehar/pistol" = "latest"
"ubi:lusingander/serie" = "latest"
starship = "latest"
usage = "latest"

# Bash
shellcheck = "latest"
# Nushell
"cargo:nu" = "latest"
"cargo:nu_plugin_compress" = "latest"
"cargo:nu_plugin_file" = "latest"
"cargo:nu_plugin_formats" = "latest"
"cargo:nu_plugin_gstat" = "latest"
"cargo:nu_plugin_inc" = "latest"
"cargo:nu_plugin_polars" = "latest"
"cargo:nu_plugin_query" = "latest"
# Rust
#rust = ["stable", "nightly"]
"ubi:rust-lang/rust-analyzer" = "latest"
"cargo:cargo-outdated" = "latest"
"cargo:cargo-expand" = "latest"
"cargo:cargo-modules" = "latest"
# Zig
zig = "latest"
"ubi:zigtools/zls" = "latest"
"pipx:zigcc" = "latest"
# Python
python = "latest"
"cargo:pylyzer" = "latest"
"pipx:ruff" = "latest"
# Node.js
node = "latest"
# Typst
typst = "latest"
"ubi:Myriad-Dreamin/tinymist" = "latest"
"cargo:typstyle" = "latest"

[env]
AR = "zig ar"
CC = "zigcc"
CXX = "zigcxx"


[settings]
experimental = true

not_found_auto_install = false
