[core.option]
initial_selection = "head"
[core.search]
ignore_case = true
fuzzy = true

[core.user_command.commands_1]
name = "git show"
commands = ["sh", "-c", "git show --color=always --oneline {{target_hash}} | delta --paging=never --width={{area_width}}"]
