# Use git program to fetch
[net]
git-fetch-with-cli = true

# Statically link C runtime for musl
[target.'cfg(target_env = "musl")']
rustflags = ["-Ctarget-feature=+crt-static"]

# Customise release profile
[profile.release]
codegen-units = 1
lto = true

# Add debug info to benchmarks
[profile.bench]
debug = true

# Customise cargo-expand
[expand]
pager = true
theme = "TwoDark"
