general {
	hide_cursor = true
	ignore_empty_input = true
}

background {
	path = screenshot
	blur_passes = 3
}

input-field {
	font_family = system-ui
	inner_color = rgba(00000000)
	outer_color = rgb(ffffff)
	font_color = rgb(ffffff)
	check_color = rgb(ffa500)
	fail_color = rgb(ff0000)

	fade_timeout = 1000
}
