general {
	hide_cursor = true
	ignore_empty_input = true
}

background {
	color = rgba(00000044)
}
label {
	text = cmd[update:0:true] [ -n '$DESC' ] && echo '<b>$DESC</b>' || echo '<b>$USER</b>'

	font_family = system-ui
	font_size = 24

	position = 0, 75
}
input-field {
	placeholder_text = Password

	font_family = system-ui
	font_color = rgb(ffffff)
	inner_color = rgba(00000000)
	outer_color = rgb(ffffff)
	check_color = rgb(ffa500)
	fail_color = rgb(ff0000)
}
label {
	text = cmd[update:1000] date +'%a %d %b %Y %T %Z'

	font_family = DSEG14 Modern

	valign = bottom
	position = 0, 20
}
