#!/usr/bin/env bash
# mise description="Use win2xcur to convert icon themes"
shopt -s nullglob

function ln_win2xcur() {
	local windows="$1"
	shift
	for linux in "$@"; do
		ln --symbolic --relative --force "$windows" "$linux"
	done
}

for theme_src in "$@"; do
	theme="$(basename "$theme_src")"
	theme_out="${root:-.}/dot-icons/$theme"
	theme_out_cursors="$theme_out/cursors"
	if [ -d "$theme_src" ]; then
		echo "$theme_src -> $theme_out"
		mkdir --parents "$theme_out_cursors"
		win2xcur -o "$theme_out_cursors" "$theme_src"/*.{cur,ani}
		pushd "$theme_out_cursors" > /dev/null || exit 1
		# SOURCE: https://github.com/khayalhus/win2xcur-batch/blob/main/map.json
		ln_win2xcur '01-Normal' \
			'arrow' \
			'default' \
			'left_ptr' \
			'top_left_arrow'
		ln_win2xcur '02-Link' \
			'hand' \
			'hand1' \
			'hand2' \
			'openhand' \
			'pointer' \
			'pointer_hand'
		ln_win2xcur '03-Loading' \
			'half-busy' \
			'left_ptr_watch' \
			'progress' \
			'wait' \
			'watch'
		ln_win2xcur '04-Help' \
			'help' \
			'left_ptr_help' \
			'question_arrow' \
			'whats_this'
		ln_win2xcur '05-Text Select' \
			'ibeam' \
			'text' \
			'xterm'
		ln_win2xcur '06-Handwriting' \
			'draft' \
			'pencil'
		ln_win2xcur '07-Precision' \
			'cross' \
			'crosshair'
		ln_win2xcur '08-Unavailable' \
			'circle' \
			'crossed_circle' \
			'dnd-no-drop' \
			'forbidden' \
			'pirate'
		ln_win2xcur '09-Location Select'
		ln_win2xcur '10-Person Select'
		ln_win2xcur '11-Vertical Resize' \
			'bottom_size' \
			'n-resize' \
			'ns-resize' \
			'row-resize' \
			's-resize' \
			'sb_v_double_arrow' \
			'size_ver' \
			'split_v' \
			'v_double_arrow'
		ln_win2xcur '12-Horizontal Resize' \
			'cool-resize' \
			'down-arrow' \
			'e-resize' \
			'ew-resize' \
			'h_double_arrow' \
			'left-arrow' \
			'left_side' \
			'right-arrow' \
			'right_side' \
			'sb_h_double_arrow' \
			'size_hor' \
			'split_h' \
			'w-resize'
		ln_win2xcur '13-Diagonal Resize 1' \
			'botton_right_corner' \
			'nw-resize' \
			'nwse-resize' \
			'se-resize' \
			'size_fdiag' \
			'top_left_corner'
		ln_win2xcur '14-Diagonal Resize 2' \
			'bottom_left_corner' \
			'size_bdiag' \
			'sw-resize' \
			'top_right_corner'
		ln_win2xcur '15-Move' \
			'all-scroll' \
			'closedhand' \
			'dnd-move' \
			'dnd-none' \
			'fleur' \
			'grab' \
			'grabbing' \
			'move'
		ln_win2xcur '16-Alternate Select' \
			'top_side' \
			'up_arrow'
		# SOURCE: https://gist.github.com/sole/571812
		ln --symbolic --relative --force 'sb_v_double_arrow' '00008160000006810000408080010102'
		ln --symbolic --relative --force 'sb_h_double_arrow' '028006030e0e7ebffc7f7070c0600140'
		ln --symbolic --relative --force 'crossed_circle' '03b6e0fcb3499374a867c041f52298f0'
		ln --symbolic --relative --force 'left_ptr_watch' '08e8e1c95fe2fc01f976f1e063a24ccd'
		ln --symbolic --relative --force 'h_double_arrow' '14fef782d02440884392942c11205230'
		ln --symbolic --relative --force 'v_double_arrow' '2870a09082c103050810ffdffffe0204'
		ln --symbolic --relative --force 'left_ptr_watch' '3ecb610c1bf2410f44200f48c40d3599'
		ln --symbolic --relative --force 'fleur' '4498f0e0c1937ffe01fd06f973665830'
		ln --symbolic --relative --force 'copy' '6407b0e94181790501fd1e167b474872'
		ln --symbolic --relative --force 'link' '640fb0e74195791501fd1ed57b41487f'
		ln --symbolic --relative --force 'hand1' '9d800788f1b08800ae810202380a0822'
		ln --symbolic --relative --force 'top_left_corner' 'c7088f0f3e6c8088236ef8e1e3e70000'
		ln --symbolic --relative --force 'question_arrow' 'd9ce0ab605698f320427677b458ad60b'
		ln --symbolic --relative --force 'hand' 'e29285e634086352946a0e7090d73106'
		ln --symbolic --relative --force 'top_right_corner' 'fcf1c3c7cd4491d801f1e1c78f100000'
		popd > /dev/null || exit 1
		cat <<-EOF > "$theme_out/index.theme"
		[Icon Theme]
		Name=$theme
		Comment=$theme converted from Windows format
		Example=default
		EOF
	else
		echo "$theme_src is not a theme folder" >&2
	fi
done
