#!/usr/bin/bash

file="$1"
export COLUMNS="$2"
export LINES="$3"
x="$4"
y="$5"

case "$(file --dereference --brief --mime-type "$file")" in
	# Display images in kitty
	image/*)
		kitty +kitten icat --stdin no --place "${COLUMNS}x${LINES}@${x}x${y}" "$file" > /dev/tty
		;;
	# Display video thumbnails in kitty
	video/*)
		ffmpegthumbnailer -i "$file" -o /dev/stdout -s 0 -m | kitty +kitten icat --stdin yes --place "${COLUMNS}x${LINES}@${x}x${y}" > /dev/tty
		;;
	# Defaults with lesspipe
	*)
		if [ "$(file --dereference --brief --mime-encoding "$file")" = 'binary' ]; then
			file "$file"
			echo
		fi
		lesspipe.sh "$file" | bat --paging never --color always --style plain --terminal-width "$COLUMNS"
		;;
esac

exit 1
