# Layout
general {
	layout = master
}
group {
	groupbar {
		font_size = 10
	}
}
misc {
	enable_swallow = true
	swallow_regex = ^(com\.mitchellh\.ghostty)$
}

# Decoration
general {
	gaps_out = 15, 15, 5, 15
}
decoration {
	rounding = 5
	shadow {
		enabled = false
	}
}
misc {
	disable_splash_rendering = true
}

# Render
render {
	direct_scanout = 2 # Auto (ON with content type "game")
	new_render_scheduling = true
}
misc {
	vrr = 2 # Fullscreen only
}
xwayland {
	force_zero_scaling = true
}

# Input
input {
	numlock_by_default = true
	touchpad {
		natural_scroll = true
	}
}
misc {
	mouse_move_enables_dpms = true
	key_press_enables_dpms = true
	middle_click_paste = false
}

# Permissions
ecosystem {
	enforce_permissions = true
}
permission = /usr/bin/grim, screencopy, allow
permission = /usr/bin/hyprlock, screencopy, allow
permission = /usr/lib/xdg-desktop-portal-hyprland, screencopy, allow

source = hyprland.conf.d/*.conf

# Quickly configure unknown monitors
monitorv2 {
	output =
	mode = preferred
	position = auto
	scale = 1
	cm = auto
}

# Deny unknown keyboards
permission = .*, keyboard, deny

misc {
	disable_autoreload = true
}
ecosystem {
	no_donation_nag = true
}
