# Rust
[[language]]
name = "rust"
indent = { unit = "\t", tab-width = 4 }
[language-server.rust-analyzer.config]
cargo.features = "all"
check.command = "clippy"
imports.prefix = "self"

# Zig
[language-server.zls.config]
enable_build_on_save = true

# Python
[[language]]
name = "python"
indent = { unit = "\t", tab-width = 4 }
language-servers = ["basedpyright", "ruff"]
formatter = { command = "ruff", args = ["format", "--quiet", "-"] }
auto-format = true

# Typst
[[language]]
name = "typst"
formatter.command = "typstyle"
auto-format = true
[language-server.tinymist.config]
exportPdf = "onSave"
formatterMode = "typstyle"

# Brioche
[[language]]
name = "brioche"
scope = "source.bri"
injection-regex = "brioche"
language-id = "brioche"
file-types = ["bri"]
roots = ["project.bri"]
grammar = "typescript"
comment-token = "//"
block-comment-tokens = { start = "/*", end = "*/" }
indent = { tab-width = 2, unit = "  " }
language-servers = ["brioche-lsp"]
[language-server.brioche-lsp]
command = "brioche"
args = ["lsp", "--stdio"]
