# Rust
[[language]]
name = "rust"
indent = { unit = "\t", tab-width = 4 }
[language-server.rust-analyzer.config]
cargo.features = "all"
check.command = "clippy"
imports.prefix = "self"

# Zig
[language-server.zls.config]
enable_build_on_save = true

# Python
[[language]]
name = "python"
indent = { unit = "\t", tab-width = 4 }
language-servers = ["basedpyright", "ruff"]
formatter = { command = "ruff", args = ["format", "--quiet", "-"] }
auto-format = true

# Typst
[[language]]
name = "typst"
language-servers = ["tinymist", "ltex-ls-plus"]
formatter.command = "typstyle"
[language-server.tinymist.config]
exportPdf = "onSave"
formatterMode = "typstyle"
