[metadata]
name = "git-log"
description = "Select git log entries"
requirements = ["git"]

[source]
command = 'git log --oneline --date=short --pretty="format:%h %s %an %cd" "$@"'
output = "{split: :0}"

[preview]
command = 'git show --patch --stat --pretty=fuller --color=always "{0}"'
