[[manager.prepend_keymap]]
desc = "Move cursor up"
on = ["k"]
run = '''
  plugin --sync arrow --args=-1
'''

[[manager.prepend_keymap]]
desc = "Move cursor down"
on = ["j"]
run = '''
  plugin --sync arrow --args=1
'''

[[manager.prepend_keymap]]
desc = "Move cursor up"
on = ["<Up>"]
run = '''
  plugin --sync arrow --args=-1
'''

[[manager.prepend_keymap]]
desc = "Move cursor down"
on = ["<Down>"]
run = '''
  plugin --sync arrow --args=1
'''

[[manager.prepend_keymap]]
desc = "Open a drag source window for the selected file"
on = ["<C-n>"]
run = '''
  shell 'dragon-drop --and-exit --on-top "$1"' --confirm
'''

[[manager.prepend_keymap]]
desc = "Maximise the preview pane"
on = ["<C-p>"]
run = '''
  plugin --sync max-preview
'''

[[manager.prepend_keymap]]
desc = "Hide the preview pane"
on = ["<A-p>"]
run = '''
  plugin --sync hide-preview
'''
