# Import the default configuration
imports = ["conf.toml"]

default_flags = "--dates --show-git-info --git-status"

[[verbs]]
invocation = "edit"
shortcut = "e"
key = "ctrl-e"
external = "$EDITOR {file}:{line}"
leave_broot = false
[[verbs]]
invocation = "git-add"
shortcut = "ga"
key = "ctrl-a"
apply_to = "file"
external = "git add {file}"
leave_broot = false
[[verbs]]
invocation = "git-unstage"
shortcut = "gu"
key = "ctrl-u"
apply_to = "file"
external = "git unstage {file}"
leave_broot = false
[[verbs]]
invocation = "git-restore"
shortcut = "gr"
key = "ctrl-r"
apply_to = "file"
external = "git restore {file}"
leave_broot = false
