line-length = 88

[lint]
ignore = [
	# Rules conflicting with ruff format
	"W191",
	"E111",
	"E114",
	"E117",
	"E501",
	"D206",
	"D300",
	"Q000",
	"Q001",
	"Q002",
	"Q003",
	"COM812",
	"COM819",
	"ISC001",
	"ISC002",
]
