[settings]
default_target_type = "symbolic"

[default]
depends = [
	"helix",
	"bash",
	"nushell",
	"starship",
	"carapace",
	"git",
	"jj",
	"gpg",
]
[default.files]
"env.d/" = "$XDG_CONFIG_HOME/environment.d/"
[default.files."env.d/80-editor.conf"]
type = "template"
target = "$XDG_CONFIG_HOME/environment.d/80-editor.conf"
if = 'editor'

[helix]
[helix.files]
"helix/" = "$XDG_CONFIG_HOME/helix/"

[sh]
[sh.files]
"sh/profile.sh" = "~/.profile"

[bash]
depends = ["sh"]
[bash.files]
"bash/profile.bash" = "~/.bash_profile"
"bash/rc.bash" = "~/.bashrc"

[nushell]
[nushell.files]
"nushell/" = "$XDG_CONFIG_HOME/nushell/"
"nushell/vendor/" = "$XDG_DATA_HOME/nushell/vendor/"
[nushell.files."nushell/env.conf"]
type = "template"
target = "$XDG_CONFIG_HOME/environment.d/89-shell.conf"
if = '(is_executable "nu")'

[starship]
[starship.files]
"starship/config.toml" = "$XDG_CONFIG_HOME/starship.toml"
[starship.files."starship/rc.bash"]
type = "symbolic"
target = "$XDG_CONFIG_HOME/bashrc.d/90-starship.bash"
if = '(is_executable "starship")'
[starship.files."starship/rc.nu"]
type = "template"
target = "$XDG_DATA_HOME/nushell/vendor/autoload/90-starship.nu"
if = '(is_executable "starship")'

[carapace]
[carapace.files]
"carapace/env.conf" = "$XDG_CONFIG_HOME/environment.d/90-carapace.conf"
[carapace.files."carapace/rc.bash"]
type = "symbolic"
target = "$XDG_CONFIG_HOME/bashrc.d/80-carapace.bash"
if = '(is_executable "carapace")'
[carapace.files."carapace/rc.nu"]
type = "template"
target = "$XDG_DATA_HOME/nushell/vendor/autoload/80-carapace.nu"
if = '(is_executable "carapace")'

[git]
[git.files]
"git/" = "$XDG_CONFIG_HOME/git/"
[git.files."git/interactive-rebase-tool.gitconfig"]
type = "symbolic"
target = "$XDG_CONFIG_HOME/git/interactive-rebase-tool.gitconfig"
if = '(is_executable "interactive-rebase-tool")'
[git.files."git/delta.gitconfig"]
type = "symbolic"
target = "$XDG_CONFIG_HOME/git/delta.gitconfig"
if = '(is_executable "delta")'
[git.files."git/serie.toml"]
type = "symbolic"
target = "$XDG_CONFIG_HOME/serie/config.toml"
[git.files."git/serie.gitconfig"]
type = "symbolic"
target = "$XDG_CONFIG_HOME/git/serie.gitconfig"
if = '(is_executable "serie")'

[jj]
[jj.files]
"jj/config.toml" = "$XDG_CONFIG_HOME/jj/config.toml"
"jj/" = "$XDG_CONFIG_HOME/jj/conf.d/"

[gpg]
[gpg.files]
"gpg/rc.bash" = "$XDG_CONFIG_HOME/bashrc.d/70-gpg.bash"
"gpg/rc.nu" = "$XDG_CONFIG_HOME/nushell/autoload/70-gpg.nu"

[ssh]
[ssh.files]
