[settings]
default_target_type = "symbolic"

[default]
depends = [
	"helix",
	"bash",
	"nushell",
	"starship",
	"carapace",
	"git",
	"jj",
	"gpg",
	"ssh",
	"fontconfig",
	"gui",
]
[default.files]
"env.d/" = "$XDG_CONFIG_HOME/environment.d/"
[default.files."env.d/80-editor.conf"]
type = "template"
target = "$XDG_CONFIG_HOME/environment.d/80-editor.conf"
if = 'editor'

[helix]
[helix.files]
"helix/" = "$XDG_CONFIG_HOME/helix/"

[sh]
[sh.files]
"sh/profile.sh" = "~/.profile"

[bash]
depends = ["sh"]
[bash.files]
"bash/profile.bash" = "~/.bash_profile"
"bash/rc.bash" = "~/.bashrc"

[nushell]
[nushell.files]
"nushell/" = "$XDG_CONFIG_HOME/nushell/"
"nushell/vendor/" = "$XDG_DATA_HOME/nushell/vendor/"
[nushell.files."nushell/env.conf"]
type = "template"
target = "$XDG_CONFIG_HOME/environment.d/89-shell.conf"
if = '(is_executable "nu")'

[starship]
[starship.files]
"starship/config.toml" = "$XDG_CONFIG_HOME/starship.toml"
[starship.files."starship/rc.bash"]
type = "symbolic"
target = "$XDG_CONFIG_HOME/bashrc.d/90-starship.bash"
if = '(is_executable "starship")'
[starship.files."starship/rc.nu"]
type = "template"
target = "$XDG_DATA_HOME/nushell/vendor/autoload/90-starship.nu"
if = '(is_executable "starship")'

[carapace]
[carapace.files]
"carapace/env.conf" = "$XDG_CONFIG_HOME/environment.d/90-carapace.conf"
[carapace.files."carapace/rc.bash"]
type = "symbolic"
target = "$XDG_CONFIG_HOME/bashrc.d/80-carapace.bash"
if = '(is_executable "carapace")'
[carapace.files."carapace/rc.nu"]
type = "template"
target = "$XDG_DATA_HOME/nushell/vendor/autoload/80-carapace.nu"
if = '(is_executable "carapace")'

[git]
[git.files]
"git/" = "$XDG_CONFIG_HOME/git/"
[git.files."git/interactive-rebase-tool.gitconfig"]
type = "symbolic"
target = "$XDG_CONFIG_HOME/git/interactive-rebase-tool.gitconfig"
if = '(is_executable "interactive-rebase-tool")'
[git.files."git/delta.gitconfig"]
type = "symbolic"
target = "$XDG_CONFIG_HOME/git/delta.gitconfig"
if = '(is_executable "delta")'
[git.files."git/serie.toml"]
type = "symbolic"
target = "$XDG_CONFIG_HOME/serie/config.toml"
[git.files."git/serie.gitconfig"]
type = "symbolic"
target = "$XDG_CONFIG_HOME/git/serie.gitconfig"
if = '(is_executable "serie")'

[jj]
[jj.files]
"jj/config.toml" = "$XDG_CONFIG_HOME/jj/config.toml"
"jj/" = "$XDG_CONFIG_HOME/jj/conf.d/"

[gpg]
[gpg.files]
"gpg/rc.bash" = "$XDG_CONFIG_HOME/bashrc.d/70-gpg.bash"
"gpg/rc.nu" = "$XDG_CONFIG_HOME/nushell/autoload/70-gpg.nu"

[ssh]
[ssh.files]
"ssh/rc.bash.d/" = "$XDG_CONFIG_HOME/bashrc.d/"
"ssh/rc.nu.d/" = "$XDG_CONFIG_HOME/nushell/autoload/"
[ssh.files."ssh/rc.bash.d/75-ssh-agent.bash"]
type = "symbolic"
target = "$XDG_CONFIG_HOME/bashrc.d/75-ssh-agent.bash"
if = '(is_executable "gpgconf")'
[ssh.files."ssh/rc.nu.d/75-ssh-agent.nu"]
type = "symbolic"
target = "$XDG_CONFIG_HOME/nushell/autoload/75-ssh-agent.nu"
if = '(is_executable "gpgconf")'

[fontconfig]
[fontconfig.files]
"fontconfig/" = "$XDG_CONFIG_HOME/fontconfig/conf.d/"

[gui]
[gui.files]
"gui/gtk3.ini" = "$XDG_CONFIG_HOME/gtk-3.0/settings.ini"
"gui/qt.conf" = "$XDG_CONFIG_HOME/environment.d/80-qt.conf"

[quickshell]
[quickshell.files]
"quickshell/" = "$XDG_CONFIG_HOME/quickshell/"
"quickshell/systemd.service" = "$XDG_CONFIG_HOME/systemd/user/quickshell@.service"

[uwsm]
[uwsm.files]
"uwsm/" = "$XDG_CONFIG_HOME/uwsm/"

[hyprland]
depends = [
	"uwsm",
	"hypridle",
	"hyprlock",
]
[hyprland.files]
"hyprland/" = "$XDG_CONFIG_HOME/hypr/"
"hyprland/uwsm.env" = "$XDG_CONFIG_HOME/uwsm/env-hyprland"

[hypridle]
[hypridle.files]
"hypridle/hypridle.conf" = "$XDG_CONFIG_HOME/hypr/hypridle.conf"

[hyprlock]
[hyprlock.files]
"hyprlock/hyprlock.conf" = "$XDG_CONFIG_HOME/hypr/hyprlock.conf"

[app2unit]
[app2unit.files]
"app2unit/uwsm.env" = "$XDG_CONFIG_HOME/uwsm/env.d/app2unit.env"

[ghostty]
[ghostty.files]
"ghostty/" = "$XDG_CONFIG_HOME/ghostty/"

[mpv]
[mpv.files]
