[default]
depends = [
	"helix",
	"bash",
	"nushell",
]
[default.files]
"env.d/" = "$XDG_CONFIG_HOME/environment.d/"
[default.files."env.d/80-editor.conf"]
type = "template"
target = "$XDG_CONFIG_HOME/environment.d/80-editor.conf"
if = 'editor'

[helix]
[helix.files]
"helix/" = "$XDG_CONFIG_HOME/helix/"

[sh]
[sh.files]
"sh/profile.sh" = "~/.profile"

[bash]
depends = ["sh"]
[bash.files]
"bash/profile.bash" = "~/.bash_profile"
"bash/rc.bash" = "~/.bashrc"

[nushell]
[nushell.files]
"nushell/" = "$XDG_CONFIG_HOME/nushell/"
